In [2]:
import pandas as pd
a=pd.read_csv('/content/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [3]:
y=a['price_range']
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64


In [4]:
x=a.drop('price_range',axis=1)
print(x)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(x)
print(xtrain_norm)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.05, random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1979           1614     0          1.2         0   1       1           9   
1273            627     1          1.6         1   3       1          12   
538             704     0          2.2         1   4       0          53   
1529           1831     1          2.2         1   4       0          55   
37             1725     1          1.6         1   6       1           6   
...             ...   ...          ...       ...  ..     ...         ...   
835            1224     1          1.6         0   9       0          33   
1216           1158     0          0.7         1   1       1          29   
1653           1190     0          2.0         1   0       0          40   
559            1191     0          2.4         1   2       0          13   
684             706     0          0.5         0  13       1          31   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1979    0

In [7]:
h=pd.read_csv('/content/heart.csv')
print(h)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [8]:
yh=h['target']
print(yh)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [9]:
xh=h.drop('target',axis=1)
print(xh)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xheart_norm=scaler.fit_transform(xh)
print(xheart_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [11]:
from sklearn.model_selection import train_test_split
xh_train, xh_test, yh_train, yh_test = train_test_split(
    x, y, test_size=0.05, random_state=0)
print(xh_train)
print(xh_test)
print(yh_train)
print(yh_test)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1979           1614     0          1.2         0   1       1           9   
1273            627     1          1.6         1   3       1          12   
538             704     0          2.2         1   4       0          53   
1529           1831     1          2.2         1   4       0          55   
37             1725     1          1.6         1   6       1           6   
...             ...   ...          ...       ...  ..     ...         ...   
835            1224     1          1.6         0   9       0          33   
1216           1158     0          0.7         1   1       1          29   
1653           1190     0          2.0         1   0       0          40   
559            1191     0          2.4         1   2       0          13   
684             706     0          0.5         0  13       1          31   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1979    0

In [17]:
import numpy as np
x1=xh_train[:,0:1]
x2=xh_train[:,0:2]
x3=xh_train[:,0:3]
x4=xh_train(3)
x5=xh_train(4)
x6=xh_train(5)
x7=xh_train(6)
x8=xh_train(7)
x9=xh_train(8)
x10=xh_train(9)
x11=xh_train(10)
x12=xh_train(11)
x13=xh_train(12)
y_p=yh_train(0)
def preceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if(s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)